### ISSUE TITLE
why not trigger the Connection::__destruct()  only for the first time?

### ISSUE THREAD

**Issue by blogdaren** [blogdaren/PHPForker#1]
https://github.com/blogdaren/PHPForker/blob/68ae2216ec9d852ca48a334f0ec3b1244c3bc874/Container.php#L1107

1.  well, first of all, the  `Connection::$connections` is an static array saved some instances of connection 
2.  just as the title described,  why **not** trigger the Connection::__destruct() when i use `unset(Connection::$connections[$cid])` **only for the first time**?

anyones's help would be appreciate

**Comment by walkor** [comment]
Try the codes.
```php
if($cid > 0) unset(Connection::$connections[$cid], $connection);
```

**Comment by blogdaren** [comment]
well, that's it, thks vevy much.

**Comment by blogdaren** [comment]
well, that's it, thks vevy much.


On 2/21/2019 10:26，walkor<notifications@github.com> wrote：

Try the codes.

if($cid>0) unset(Connection::$connections[$cid], $connection);
