### ISSUE TITLE
In the resetStd() method, this line of code self::setOutputStream($STDOUT); in the Base class is the private control permission, but you use the Container as protected.

### ISSUE THREAD

**Issue by twomiao** [blogdaren/PHPForker#2]
Base code: static **_private_** function setOutputStream($stream = null)
Reset() method error code: self::setOutputStream($STDOUT);

**So:** static private function setOutputStream($stream = null) is changed to static protected function setOutputStream($stream = null)

**Comment by blogdaren** [comment]
tks, fixed already.
